### ISSUE TITLE
[doc] Add doc about internal implementation

### ISSUE THREAD

**Issue by gaocegege-caicloud** [caicloud/kubeflow-controller#21]
Low priority

## Local Mode

```
TFJob <-> Pod
CRD
```

## Distributed Mode

```
TFJob <-> Pods and Services(worker), RS(ps)
```

We need a way to specify the cluster spec for tf jobs and pass it into the code.

**Comment by DjangoPeng** [comment]
I think we have fixed the issue, right? @gaocegege-caicloud

**Comment by gaocegege-caicloud** [comment]
I am closing it
